### 다층 퍼셉트론으로 손글씨 분류하기

#### (1) 데이터셋 살펴보기

In [15]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

- 첫 번째 샘플 출력. 0보다 큰 숫자들을 검정색 점이라고 상상해보면 숫자 0의 실루엣처럼 보인다.

In [2]:
print(digits.images[0])

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


In [4]:
print(digits.target[0])

0


In [5]:
print('전체 샘플 수 : {}'.format(len(digits.images)))

전체 샘플 수 : 1797


- digits.data는 8x8 행렬로 저장된 digits.images를 64차원의 벡터로 변환해서 저장한 형태이다.

In [7]:
print(digits.data[0])

[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]


In [8]:
X = digits.data
Y = digits.target

#### (2) 다층 퍼셉트론 분류기 만들기

In [9]:
import torch
import torch.nn as nn
from torch import optim

In [10]:
model = nn.Sequential(
nn.Linear(64, 32),  #input layer = 64, hidden layer = 32
nn.ReLU(),
nn.Linear(32, 16),  #input layer = 32, hidden layer = 16
nn.ReLU(),
nn.Linear(16, 10)   #input layer = 16, output layer = 10
)

In [11]:
X = torch.tensor(X, dtype = torch.float32)
Y = torch.tensor(Y, dtype = torch.int64)

In [13]:
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())
losses = []

In [14]:
for epoch in range(100):
    optimizer.zero_grad()
    y_pred = model(X)
    loss = loss_fn(y_pred, Y)
    loss.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        print('Epoch {:4d} / {} Cost : {:.6f}'.format(epoch, 100, loss.item()))
    losses.append(loss.item())

Epoch    0 / 100 Cost : 2.531521
Epoch   10 / 100 Cost : 2.202123
Epoch   20 / 100 Cost : 2.011299
Epoch   30 / 100 Cost : 1.757547
Epoch   40 / 100 Cost : 1.514845
Epoch   50 / 100 Cost : 1.239010
Epoch   60 / 100 Cost : 0.946705
Epoch   70 / 100 Cost : 0.683194
Epoch   80 / 100 Cost : 0.482657
Epoch   90 / 100 Cost : 0.355184
