## nn.Module로 구현하는 Logistic regression

간단하다. H(x) = sigmoid(Wx + b)를 nn.sigmoid()를 통해 학습하면 된다.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [4]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [6]:
model = nn.Sequential(nn.Linear(2,1),
                     nn.Sigmoid()
                     )

In [7]:
model(x_train)

tensor([[0.3600],
        [0.2872],
        [0.6801],
        [0.4389],
        [0.5216],
        [0.7473]], grad_fn=<SigmoidBackward0>)

In [8]:
optimizer = optim.SGD(model.parameters(), lr = 1)

EPOCH = 1000

for epoch in range(EPOCH + 1):
    
    hypothesis = model(x_train)
    
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum() / len(correct_prediction)
        print('Epoch {:4d}/{}, Cost : {:.6f}, Accuracy : {:2.2f}%'.format(epoch, EPOCH, cost.item(), accuracy*100))

Epoch    0/1000, Cost : 0.614994, Accuracy : 66.67%
Epoch  100/1000, Cost : 0.140280, Accuracy : 100.00%
Epoch  200/1000, Cost : 0.082549, Accuracy : 100.00%
Epoch  300/1000, Cost : 0.058858, Accuracy : 100.00%
Epoch  400/1000, Cost : 0.045878, Accuracy : 100.00%
Epoch  500/1000, Cost : 0.037649, Accuracy : 100.00%
Epoch  600/1000, Cost : 0.031951, Accuracy : 100.00%
Epoch  700/1000, Cost : 0.027766, Accuracy : 100.00%
Epoch  800/1000, Cost : 0.024558, Accuracy : 100.00%
Epoch  900/1000, Cost : 0.022020, Accuracy : 100.00%
Epoch 1000/1000, Cost : 0.019960, Accuracy : 100.00%


In [9]:
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2477, 1.5151]], requires_grad=True), Parameter containing:
tensor([-14.4576], requires_grad=True)]
